# Generated by Django 5.1.2 on 2024-10-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfOrder', models.DateField()),
                ('AddressOfPickup', models.CharField(max_length=500)),
                ('AddressOfWaypoint', models.CharField(max_length=500)),
                ('AddressOfDelivery', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
                ('CustomerName', models.CharField(max_length=500)),
                ('DateOfOrder', models.DateField()),
            ],
        ),
    ]
